### ISSUE TITLE
Proof state not shown

### ISSUE THREAD

**Issue by joonazan** [leanprover-community/vscode-lean4#11]
I have installed Lean 4 using Nix. Based on the source code I thought that there should be some window showing the proof goal but there isn't. Is this a bug or do I have to explicitly open it somehow?

**Comment by mhuisi** [comment]
Yes, but it seems that the pinned version in Nix is [out of date](https://github.com/leanprover/lean4/blob/95183e4e6045371a3757afe109fae209293f350b/nix/packages.nix#L61).
It references the old version of vscode-lean4 that was published on my own user account, whereas it is now published under the `leanprover` account. `mhuisi.lean4` was effectively version 0.0.0 of `leanprover.lean4` :)
(cc @Kha)

**Comment by Kha** [comment]
Oof, so there are two v0.0.6? Fixed.
