### ISSUE TITLE
Make use of fullRange when selecting messages in info view

### ISSUE THREAD

**Issue by Kha** [leanprover-community/vscode-lean4#16]
For a lack of `end`, errors such as "unclosed goal" are shown on the initial token of a tactic block, e.g. `by` instead. However, we now set an additional diagnostic field `fullRange` to the whole range of the block and use it in lean4-mode to select messages for the current location: https://github.com/leanprover/lean4/commit/3eb91d4950b6fd2d526c00f2d03e56168614cc37
Now I have no idea if VS Code also just forwards the response objects without removing unexpected fields... if it does not, I suppose this could get tricky.

**Comment by gebner** [comment]
So the idea is that the info view should show all messages whose fullRange contains the current position?

> if it does not, I suppose this could get tricky.

I believe we could support this by monkey-patching the protocol2CodeConverter to copy the field.  But I haven't tried it.

**Comment by Kha** [comment]
> So the idea is that the info view should show all messages whose fullRange contains the current position?

Yes! I've later refined the logic in lean4-mode to sort these messages by `fullRange.end.line` so that error for the current tactic are shown before errors for the tactic block: https://github.com/leanprover/lean4/commit/f4ed9686aaf3aba85a5dbd35410f23ec7305f3f8#diff-5e202350237446f75417cbbcdf675e85ac917917f9a3af357ee5fdccc4f3f2a7R81

**Comment by Kha** [comment]
:tada:
