### ISSUE TITLE
Imports fail with 'no such file or directoy'

### ISSUE THREAD

**Issue by tydeu** [leanprover-community/vscode-lean4#22]
When running Lean 4 nightly (commit `26dda3f63d88`) with `vscode-lean4` v0.0.24 on Windows, I am encountering the following error on any `import`:

```
`leanpkg print-paths` failed:

stderr:
configuring <package>
> sh -c "<home>\.elan\toolchains\leanprover-lean4-nightly\bin/leanmake" LEAN_OPTS="" LEAN_PATH="././build" "build\<Foo.olean>" >&2    # in directory .
uncaught exception: no such file or directory (error code: 2)
```

It seems to be failing because it is adding `build` both to `LEAN_PATH` and to the path of `Foo.olean`. Reopening VS Code, reloading the window, restarting the lean server, and/or refreshing the dependencies does not fix the issue. 

Furthermore, running `leanpkg print-paths` myself in the directory works:
```
$ leanpkg print-paths
configuring <package>
././build
./.
```
So I am not quite sure what is going on.

However, I can report that this error is not present when using the stable build of Lean 4.

**Comment by Kha** [comment]
The missing file is most likely `sh`, which would explain why it's not failing in your bash. And no, we really shouldn't depend on `sh` and `make` on Windows. I will likely revisit that part of `leanpkg` soon.

Note that this is an issue with Lean, not vscode-lean4.

**Comment by tydeu** [comment]
@Kha Which part is calling `sh`? Because I can run `leanpkg print-paths` fine within the VS Code integrated terminal (which I have setup to be MSYS2). Is `vscode-lean4` running `leanpkg print-paths` or is this some process spawned by lean? If `vscode-lean4` is running it, it should be able to inherit the environment of the integrated terminal and work correctly. 

Also, why is this just a problem with the nightly, but not with the stable release? Did the `sh` dependency come later?

**Comment by Kha** [comment]
The Lean server is now calling `leanpkg print-paths`, which will call `sh/make`, by itself to make sure that imports are up to date. So if VS Code itself (and not its terminals) does not have `sh` in its PATH, neither will the Lean server and leanpkg started from it, leading to the error. Meaning you could running VS Code (after closing all instances) from *inside* an msys2 shell and it should work, possibly?

**Comment by tydeu** [comment]
@Kha Running VS Code inside a msys2 shell does work. However, this completely messes with my environment. This problem could be better resolved if I could configure the environment of the Lean server process. Luckily, while digging through the extension codebase, I found that this can be done. 

https://github.com/leanprover-community/vscode-lean4/blob/fe305e0f673ba3fad169b4fae5998bcdca75eedd/src/leanclient.ts#L64-L74

All I need is to be able to is to able to add to the path variable of the `env` option. I can even offer to add the feature myself if that is desired.
