### ISSUE TITLE
Had to remove extension from ~/.vscode to restore lean-community functionality

### ISSUE THREAD

**Issue by kevinsullivan** [leanprover-community/vscode-lean4#5]
Feel free to nix this "experience/problem report". 

I installed lean4 and this extension and used elan override set to set lean4 as the language for a small test project. It seemed to work. Problem was that once I returned to a lean-community-lean3 project, VS Code thought I was still working on a lean4 project. This remained the case even after I disabled this extension. And indeed opening settings and searching for lean showed a bunch of lean4 settings, even though I'd disabled the extension. I was able to restore functionality for editing Lean3 files (only) by manually deleting the lean4 extension directory from ~/.vscode/extensions. I'm no expert on extension engineering, but maybe some cleanup upon disabling the extension is needed -- or an option to remove and not just disable it?

I see in the latest documentation (GitHub) on the lean3 extension that it's meant to be able to co-exist with the lean4 extension, but I wasn't able to get everything working.

**Comment by gebner** [comment]
Which versions of the lean/lean4 extensions are you using?  (ctrl-shift-x opens the extensions)
The "coexistence" features requires relatively new versions of *both* extensions.

The lean4 extension is now available via the marketplace, so you don't need to compile it yourself anymore.

As a workaround, you can enable/disable extensions per workspace (= project).  In the extensions panel, just right-click on the extension and you can then "Disable (Workspace)".

**Comment by kevinsullivan** [comment]
I had installed lean 4 extension a few days after the lean workshop, via
the marketplace. Issue might well have been obsoleted by more recent
updates. If others are ok let's just ignore. I'm back to lean 3 to teach
this term. Will try 4 again soon enough. Thanks. K

**Comment by mhuisi** [comment]
It should be OK once you reinstall the Lean 4 extension from the marketplace. If it isn't, feel free to open another issue! :)
