### ISSUE TITLE
"Watchdog error: Got unknown document URI"

### ISSUE THREAD

**Issue by bryangingechen** [leanprover-community/vscode-lean4#9]
The following is with `Lean (version 4.0.0-nightly-2021-02-13, commit 172d47c468fb, Release)` on macOS and `vscode-lean4` 0.0.6.

When I use go to definition on a declaration that leads to a different file, the server sometimes dies with after the following log messages. It also happens (rarely) when I start the extension.

```text
[Trace - 9:07:02 PM] Sending notification 'textDocument/didOpen'.
[Error - 9:07:02 PM] Connection to server is erroring. Shutting down server.
[Error - 9:07:02 PM] Connection to server is erroring. Shutting down server.
[Trace - 9:07:02 PM] Sending request 'shutdown - (20)'.
[Error - 9:07:02 PM] Connection to server is erroring. Shutting down server.
[Error - 9:07:02 PM] Connection to server is erroring. Shutting down server.
Watchdog error: Got unknown document URI (file:///Users/bryan/.elan/toolchains/leanprover-lean4-nightly/lib/lean/src/Init/Data/String/Basic.lean)
```
(The file path there is perfectly valid; I can even cmd+click the link in VS Code and it opens the correct file.)

After this happens, I can't restart the server anymore with the "Lean 4: Restart server" command. I have to close and reopen the VS Code window.

Unfortunately, it doesn't seem very consistent, but I seem to be able to trigger it by using go to definition a few times.

**Comment by mhuisi** [comment]
On my end, it seems like b4a21f8 fixes the issue. Can you try with that commit?

**Comment by bryangingechen** [comment]
@mhuisi Thanks! I don't seem to be able to trigger the bug anymore either.
